spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patshop?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat

  resources:
    static-locations: classpath:/img/
  jackson:
    serialization:
      write-dates-as-timestamps: true
  servlet:
    multipart:
      # 启用
      enabled: true
      # 上传文件单个限制
      max-file-size: 20MB
      # 总限制
      max-request-size: 100MB

mybatis:
  type-aliases-package: com.hqb.patshop.mbg.dao
  mapper-locations: classpath:dao/generator/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

debug: true
